### ISSUE TITLE
[question]: Do we need to change somenthing somewhere for Android 13 and new opt-in for push notifications?

### ISSUE THREAD

**Issue by dcesca** [OneSignal/onesignal-expo-plugin#114]
Hi,
I've read this and I was wondering if there's somenthing we'd need to change somewhere to support this:
https://onesignal.com/blog/android-13-whats-changing-and-how-to-stay-in-touch-with-your-users/

Thanks

### OneSignal Expo SDK version

1.0.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @dcesca!  We have a specific page in our documentation that should walk you through it in more detail [here](https://documentation.onesignal.com/docs/android-13-push-notification-developer-update-guide).

Note that OneSignal recommends setting the `compileSdkVersion` and `targetSdkVersion` to `33` as it gives the most flexibility and control when requesting notification permissions.  The expo default is currently `31`, however the [expo-build-properties plugin](https://docs.expo.dev/versions/v45.0.0/sdk/build-properties/) allows you to override these defaults!

Please let me know if you have any additional questions.

**Comment by jurica-penjgusic** [comment]
Expo build properties are available only from sdk 45, is there any chance to modify compileSdkVersion without expo build properties?

**Comment by brismithers** [comment]
@jurica-penjgusic  The other new methods I know of are to switch to a bare workflow, or create a plugin which tweaks these (similar to the build properties plugin).

If you do not modify `compileSdkVersion` and `targetSdkVersion` to `33`, and leave it at the default of `31`, my understanding is an Android 13 user will be immediately prompted for push notification permission, rather than give the developer control over when to prompt the user.

Hope this helps!
