### ISSUE TITLE
[Bug]: Could not load RNOneSignal native module. Make sure native dependencies are properly linked.

### ISSUE THREAD

**Issue by mohammad6vakili** [OneSignal/onesignal-expo-plugin#145]
### What happened?

Hello
I am trying to implement One Signal on my Expo application without ejecting my application.
I followed all the steps in the document but I get an error.
`Could not load RNOneSignal native module. Make sure native dependencies are properly linked.`
After a little search, I found out that many users encountered such a problem and could not implement One Signal on their Expo application.
Is it possible to help me quickly to solve my problem?

### Steps to reproduce?

```Markdown
"onesignal-expo-plugin": "^1.1.2",
"react-native-onesignal": "^4.4.1",
"expo": "~46.0.7",
"expo-constants": "~13.2.4",
```

### What did you expect to happen?

I expected to plugin works well

### OneSignal Expo SDK version

1.1.2

### Platform

Android

### Relevant log output

```Shell
ERROR  Could not load RNOneSignal native module. Make sure native dependencies are properly linked.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @mohammad6vakili !  I suspect you are trying to run your app in the Expo Go environment which is unfortunately **not** a supported environment due to OneSignal depending on a native module.  Please make sure you are building and running in one of the supported environments: 

[The Expo run commands](https://docs.expo.dev/workflow/customizing/) (expo run:[android|ios])
[Custom clients](https://blog.expo.dev/introducing-custom-development-clients-5a2c79a9ddf8)
[EAS Build](https://docs.expo.dev/build/introduction/)

Thanks!
