### ISSUE TITLE
Missing Push Capability in IOS TestFlight

### ISSUE THREAD

**Issue by daniimd** [OneSignal/onesignal-expo-plugin#160]
### How can we help?

I'm trying to integrate one signal push in my project, but I'm not getting the notifications on the IOS device. I made a compilation and I'm testing it through TestFlight.
Can someone help me? This is the message I get on onesignal

![err](https://user-images.githubusercontent.com/36265891/222521763-950c7d6d-d1c5-436a-bad0-ae63a2f8ccb8.png)

### OneSignal Expo SDK version

SKD 46

### Platform

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @daniimd can you confirm you are running on a physical device and not the simulator?  Assuming this is on a device, this typically happens when there is an entitlement or certificate issue.  A couple thoughts:

1. Ensure you've created/configured your [iOS Push Certificate](https://documentation.onesignal.com/docs/generate-an-ios-push-certificate) or your [P8 Authentication Token](https://documentation.onesignal.com/docs/establishing-an-apns-authentication-key). P8 is recommended.
2. If you run `expo prebuild` and go to `<base_path>/ios/<your_app>/<your_app>.entitlements` you should see an entry for `aps-environment`.

Please let me know if the above look okay, and we'll go from there. Thanks!

**Comment by daniimd** [comment]
> Hi @daniimd can you confirm you are running on a physical device and not the simulator? Assuming this is on a device, this typically happens when there is an entitlement or certificate issue. A couple thoughts:
> 
> 1. Ensure you've created/configured your [iOS Push Certificate](https://documentation.onesignal.com/docs/generate-an-ios-push-certificate) or your [P8 Authentication Token](https://documentation.onesignal.com/docs/establishing-an-apns-authentication-key). P8 is recommended.
> 2. If you run `expo prebuild` and go to `<base_path>/ios/<your_app>/<your_app>.entitlements` you should see an entry for `aps-environment`.
> 
> Please let me know if the above look okay, and we'll go from there. Thanks!

Hi!! Thanks for your help.
After doing all the settings according to the P8 Authentication Token documentation and now I'm getting this message:

![signal](https://user-images.githubusercontent.com/36265891/224037119-72124d74-b9d7-45d3-a15a-f300daf456d1.png)

**Comment by brismithers** [comment]
Thanks for the update @daniimd.  Within your application are you either requesting push permissions yourself, or using the OneSignal SDK to request permission?

```
OneSignal.promptForPushNotificationsWithUserResponse(true, response => {
                    // callback code
                });
```

**Comment by RL-Jurica-Penjgusic** [comment]
is this PR [https://github.com/OneSignal/onesignal-expo-plugin/pull/175](url) will fix this issue ?

**Comment by emawby** [comment]
@RL-Jurica-Penjgusic Are you still experiencing this issue with the above suggestions implemented? I am not sure if that PR will fix this issue.

**Comment by RL-Jurica-Penjgusic** [comment]
We have  40% successfull build rate. IOS build takes about 40 minutes and we pray that entitlements are included :)

**Comment by RL-Jurica-Penjgusic** [comment]
@brismithers Maybe we can close this issue. We have built over 20+ apps and none of them had issues with missing push capability after version 1.3.2 of expo one plugin.
