### ISSUE TITLE
[question]: Erro no eas buid onesignal

### ISSUE THREAD

**Issue by ValdemiroValid** [OneSignal/onesignal-expo-plugin#222]
### How can we help?

Boa tarde, estou tentando fazer um build com expo utilizado a biblioteca onesignal no expo .
O meu app.json esta assim.
 "extra": {
      "oneSignalAppId": "396c8a6c-4943-49ab-8b28-51e1309f71cb",
      "eas": {
        "projectId": "396c8a6c-4943-49ab-8b28-51e1309f71cb"
      }
    },
    "plugins": [
      "onesignal-expo-plugin",
      {
        "mode": "development"
      }
    ]
    
mas na hora do build recebo a seguinte mensagem.

You are trying to use the OneSignal plugin without any props. Property "mode" is required. Please see https://github.com/OneSignal/onesignal-expo-plugin for more info.

### OneSignal Expo SDK version

2.0.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wilkinsonj** [comment]
Try this:

**Comment by jennantilla** [comment]
Hello there! Apologies that this issue has gone stale--did the above suggestion work for you? I'm going to close this issue since it's been some time since the latest activity. Is this is still a problem on the [latest SDK version](https://github.com/OneSignal/onesignal-expo-plugin/releases/tag/2.0.3), please open a new issue and we'll be happy to assist. Thanks!
