### ISSUE TITLE
Two notifications on Android Devices - expo

### ISSUE THREAD

**Issue by CristianHourcadeBit** [OneSignal/onesignal-expo-plugin#30]
Hey! We was trying this tool in a development environment and the SDK works fine. But when we went to production and sent our first notification push, we saw that notifications appears twice on android devices, the first one is just an icon of our app with the name, and the second one is the original push sent from OneSignal dashboard. I'd like to know if you tried it out, and if you know some solution for this. Right now we're using expo-notification and OneSignal SDK in the same time... Maybe isn't compatible? 

This was tested on Android devices, using expo with the expo-notification module and OneSignal SDK/Plugin.

**Comment by rgomezp** [comment]
Howdy,
Why are you using both expo-notification AND OneSignal? I think that is most likely the issue.

**Comment by gitteraz** [comment]
@CristianHourcadeBit I have experienced the same after adding onesignal to an expo project that already used FCM push notifications. Removing FCM credential and expo push implementation solved the problem.

**Comment by rgomezp** [comment]
Enjoy!

**Comment by developersunesis** [comment]
Although this has been closed and over a year now. I stumbled on this conversation because I was experiencing the same and funny enough the same day a year later.

After considering the option provided by @\gitteraz (i.e. removing one of the sdks) I later figured out that using a background task, you could dismiss the duplicate notification triggered by `expo-notifications` when a Onesignal push notification is received.

Here's a snippet of what I did, using expo background task (https://docs.expo.dev/versions/latest/sdk/notifications/#handling-incoming-notifications-when-the-app-is-1) someone else might find it helpful:
````
TaskManager.defineTask("BACKGROUND_NOTIFICATION_TASK", ({data, error, executionInfo}) => {
        // Dismiss background message from OneSignal
        if (data && data?.notification && data?.notification?.messageId && data?.notification?.data
            && data?.notification?.data.custom.includes("\"i\":")) {
            Notifications.dismissNotificationAsync(data.notification.messageId).catch(console.warn)
        }
    })
    Notifications.registerTaskAsync("BACKGROUND_NOTIFICATION_TASK").catch(console.warn)
````

This implementation above follows https://documentation.onesignal.com/docs/duplicated-notifications, where notifications sent from Onesignal have an "i" custom property, so the background task check for this property and  if the condition is satisfied, it dismisses the duplicate notification. Also, note that there's a tendency for the notification to get displayed for a split second before getting dismissed.
