### ISSUE TITLE
OneSignalNotificationServiceExtension provisioning profile?

### ISSUE THREAD

**Issue by raunaqsingh2020** [OneSignal/onesignal-expo-plugin#40]
Hi, I am getting the following Fastlane error when I try to build for iOS (`eas build --profile development --platform ios`):

❌  error: No profiles for '*bundle id*.OneSignalNotificationServiceExtension' were found: Xcode couldn't find any iOS App Development provisioning profiles matching '*bundle id*.OneSignalNotificationServiceExtension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'OneSignalNotificationServiceExtension' from project '***')

Do I have to manually create an additional identifier (<bundle id>.OneSignalNotificationServiceExtension) and then a provisioning profile for this?

The plugin works perfectly when I comment all the OneSignal related code out before the build, and then uncomment it all after running `expo start --dev-client`.

Thanks so much!

**Comment by rgomezp** [comment]
Howdy,
To answer your question, you shouldn't need to create an additional identifier for the NSE. This is done for you automatically. The provisioning profile should be an XCode Managed Profile if automatic signing is on (which it should be). Try visually inspecting the Signing and Capabilities configuration in the Xcode workspace. You should have:
- Team: `<your team>`
- Bundle Identifier: `<your bundle id>` AND `<your bundle id>.OneSignalNotificationServiceExtension`

It sounds like something in your environment is preventing automatic signing as I'm not seeing that error on my end.

**Comment by raunaqsingh2020** [comment]
Hmm, any way I can check that if I have a managed workflow?

**Comment by rgomezp** [comment]
![Screen Shot 2021-12-30 at 3 23 04 PM](https://user-images.githubusercontent.com/11739227/147788913-3ab3b515-f782-4046-afb6-ec8af6305e87.png)

**Comment by raunaqsingh2020** [comment]
When I try building the native project (`expo run:ios`), I get the following:

```
Failed to build iOS project. "xcodebuild" exited with error code 65.
To view more error logs, try building the app with Xcode directly, by opening /Users/raunaqsingh/Developer/canada-goose/ios/DP.xcodeproj.

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/raunaqsingh/Developer/canada-goose/ios/DP.xcodeproj -configuration Debug -scheme DP -destination id=079A8E83-0A88-4223-8185-61FA54F6734A

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning
Analyze workspace

Create build description
Build description signature: 5c9947c631b8dc214ce840dc1724b44c
Build description path: /Users/raunaqsingh/Library/Developer/Xcode/DerivedData/DP-chreouiuptppyzbmrutwxoddflad/Build/Intermediates.noindex/XCBuildData/5c9947c631b8dc214ce840dc1724b44c-desc.xcbuild

note: Build preparation complete
note: Building targets in dependency order
/Users/raunaqsingh/Developer/canada-goose/ios/Pods/Target Support Files/Pods-DP/Pods-DP.debug.xcconfig:1:1: error: unable to open file (in target "DP" in project "DP")
/Users/raunaqsingh/Developer/canada-goose/ios/Pods/Target Support Files/Pods-DP/Pods-DP.debug.xcconfig:1:1: error: unable to open file (in target "DP" in project "DP")
/Users/raunaqsingh/Developer/canada-goose/ios/Pods/Target Support Files/Pods-DP/Pods-DP.debug.xcconfig:1:1: error: unable to open file (in target "DP" in project "DP")
/Users/raunaqsingh/Developer/canada-goose/ios/Pods/Target Support Files/Pods-DP/Pods-DP.debug.xcconfig:1:1: error: unable to open file (in target "DP" in project "DP")


objc[6180]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x20b75fb78) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10cfb02c8). One of the two will be used. Which one is undefined.
objc[6180]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x20b75fbc8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10cfb0318). One of the two will be used. Which one is undefined.
2021-12-30 16:43:05.279 xcodebuild[6180:3594115] warning:  The file reference for "OneSignalNotificationServiceExtension" is a member of multiple groups ("Pods" and ""); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
** BUILD FAILED **

```

It does create an `.xcodeproj` and the `<your bundle id>.OneSignalNotificationServiceExtension` is there, but it does not create a `.xcworkspace`

Could the `The file reference for "OneSignalNotificationServiceExtension" is a member of multiple groups ("Pods" and ""); this indicates a malformed project.` warning be the problem? If you want to take a look at the project, it's here: https://github.com/dailypenn/canada-goose.

Thanks so much!

**Comment by jparksecurity** [comment]
@rgomezp we're having the same issue.

We pass ios credential files when we run EAS build. Do you think if it is something to do with this?

Does anyone know if setting `credentialsSource` to local in `eas.json` turns off automatic signing?

**Comment by raunaqsingh2020** [comment]
I didn't set `credentialsSource` and still have the issue.

**Comment by jparksecurity** [comment]
@ raunaqsingh2020 Thanks for sharing your config. Then I guess `credentialsSource` is less likely the problem.

FYI I think `expo prebuild --platform ios --clean` generates `.xcworkspace` file.

You can follow rgomezp's instruction to check the bundle identifier by opening Xcode with the file.

**Comment by raunaqsingh2020** [comment]
is there any update as to whether this is an issue with the plugin or our setups? thanks again!

**Comment by russriser** [comment]
I don't have Xcode (I work on PC), I rely on EAS Build to build my ios apps. 

So, I have no idea how to verify if automatic signing is the issue. And if it were, I don't know how to fix it.

**Comment by lisaah** [comment]
Just adding another point of anecdata, also seeing this error. It seems like automatic signing is disabled when running our eas managed build based on the error message (no issues for android build). However, when I run `expo prebuild --platform ios --clean`, the workspace shows says automatically manage signing is enabled. Onesignal bundle identifier is not there.

![image](https://user-images.githubusercontent.com/3603130/148490428-0f6259f5-645b-475f-aa81-619d5b23df11.png)

**Comment by r1cs1** [comment]
I was running into the same issue. To resolve this issue first I had to create another bundle identifier and provisioning profile as stated [here](https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup#check-your-provisioning-profiles-are-setup). I've missed this first.

Then I also had to setup credential source to local with multi target credentials.json as it is [here](https://docs.expo.dev/app-signing/local-credentials/#multi-target-project) because EAS didn't pull the extensions provisioning profile even if that was submitted from the credentials.json to EXPO (That wasn't straightforward either). Or if I don't want to use local credentials then I had to run `expo prebuild --platform ios --clean`

```
{
  "android": {
    ...
  },
  "ios": {
    "<<APPNAME>>": {
      "distributionCertificate": {
        "path": "***",
        "password": "***"
      },
      "provisioningProfilePath": "***"
    },
    "OneSignalNotificationServiceExtension": {
      "distributionCertificate": {
        "path": "***",
        "password": "***"
      },
      "provisioningProfilePath": "***"
    }
  }
}

```

Now it gave me a new error commented [here](https://github.com/OneSignal/onesignal-expo-plugin/issues/21#issuecomment-992680434)

To resolve this I had to [patch](https://www.npmjs.com/package/patch-package) the `onesignal-expo-plugin` to use the same iOS target as the expo sdk. (12.0 for my case).

If anyone knows what I've missed in order to skip these patches to get it to work I'd appreciate it :)

**Comment by seyaobey-dev** [comment]
Hi. I'm facing same issue, same error. But I rely completely on (remote) `eas build` to build my ios app. I do not have Xcode locally to try to visually inspect the Signing and Capabilities configuration in the Xcode workspace. I cannot run `expo prebuild --platform ios --clean`

**Comment by raunaqsingh2020** [comment]
@r1cs1 

Hey I tried to follow your comment. Here's what I have right now:

Identifiers:
- `com.thedailypennsylvanian.mobileapp`
- `com.thedailypennsylvanian.mobileapp.OneSignalNotificationServiceExtension`

Profiles:
- `com.thedailypennsylvanian.mobileapp.profile`
- `com.thedailypennsylvanian.OneSignal.profile`

My credentials.json is similar to what you did but I am now receiving the following errors:

```
❌  error: Provisioning profile "com.thedailypennsylvanian.OneSignal.profile" doesn't support the group.com.thedailypennsylvanian.mobileapp.onesignal App Group. (in target 'OneSignalNotificationServiceExtension' from project 'DP')
```
```
❌  error: Provisioning profile "com.thedailypennsylvanian.OneSignal.profile" doesn't match the entitlements file's value for the com.apple.security.application-groups entitlement. (in target 'OneSignalNotificationServiceExtension' from project 'DP')
```

Did you get any these errors as well? and if so, how did you resolve them?

thanks!

**Comment by r1cs1** [comment]
The bundle identifier for onesignal must have the same app group entitlement setting as your mobile app.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rgomezp** [comment]
Howdy y'all,
Thanks for the details.

@r1cs1 Regarding the [error](https://github.com/OneSignal/onesignal-expo-plugin/issues/21#issuecomment-992680434) with related to Pods, the latest release (beta 9) now includes the ability to configure which deployment target the NSE should use. This needs to match the version in the generated Podfile. 

[iOS 10 was dropped in Expo 41](https://blog.expo.dev/expo-sdk-41-12cc5232f2ef) and [iOS 11 was dropped in Expo 43](https://github.com/expo/expo/pull/14383).

Thus, a custom patch is no longer needed.

@raunaqsingh2020 ,
As r1cs1 mentioned, the bundle id for OneSignal must have the same app group entitlement setting as the mobile app. It appears as if your entitlements got mixed up somehow.

---

For context, the app group is added for you automatically by the plugin based on the `bundleIdentifier` config param in your app config file as follows `group.<your bundle id>.onesignal` and should be the same across both targets.

**Comment by javascripter** [comment]
I still see the eas build error below with  beta 9, with my app configured with automatically managed credentials. 
```
❌  error: No profiles for 'com.xxx.OneSignalNotificationServiceExtension' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.xxx.OneSignalNotificationServiceExtension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'OneSignalNotificationServiceExtension' from project 'XXXX')
```

`eas.json`
```
    "beta": {
      "developmentClient": true,
      "credentialsSource": "remote",
      "distribution": "internal",
      "env": {
        "APP_ENV": "beta"
      }
    },
```

`app.config.js`

```
plugins:[
      'onesignal-expo-plugin',
      {
        mode: process.env.NODE_ENV || 'development',
        devTeam: 'XXXXX',
        iPhoneDeploymentTarget: '12.0', // Keep in sync with the value in ios/Podfile
      },
    ]
```

**Comment by frossetto** [comment]
> ignalNotificationServiceExtension' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.xxx.OneSignalNotificationServiceExtension'. Automatic signing is disab

I also see the same error with beta 9, any luck so far with this issue?

**Comment by rgomezp** [comment]
Howdy folks,
I'm sorry to hear you're still having issues.

Perhaps [this article](https://documentation.onesignal.com/docs/generate-an-ios-push-certificate) will help. Please let me know and I will do my best to try to get to the bottom of this.

**Comment by dynamiccarrots** [comment]
I am also having this issue, I have let EAS do everything for me including creating the profiles and certificates yet this error is still happening. 

We really want to use One Signal for our new app.

**Comment by frossetto** [comment]
> Howdy folks, I'm sorry to hear you're still having issues.
> 
> Perhaps [this article](https://documentation.onesignal.com/docs/generate-an-ios-push-certificate) will help. Please let me know and I will do my best to try to get to the bottom of this.

Just following up @rgomezp, I think the issue is actually with EAS rather than this repo. Even after following up the provisioning profile setup, EAS fails to build the app. But building it with `expo build`, the build proceeds and I'm able to run it in dev mode.[The production build will not properly run, being stuck on the splash screen.](https://github.com/OneSignal/onesignal-expo-plugin/issues/51)

**Comment by rgomezp** [comment]
@frossetto ,
Thanks for that info.

I found the following resources on Expo's site:
- https://docs.expo.dev/push-notifications/push-notifications-setup/#credentials
- https://docs.expo.dev/app-signing/managed-credentials/#generating-app-signing-credentials
- https://docs.expo.dev/app-signing/app-credentials/#provisioning-profiles

If the issue is with EAS as you mention, I'd recommend you go through each of those thoroughly to make sure you have covered all the requirements.

---

# Did you succeed?
@raunaqsingh2020 @r1cs1 @seyaobey-dev @lisaah @jparksecurity @javascripter @russriser

I'd like to gauge the level of success from everyone else while building with EAS. Has _anyone_ here been able to successfully set up EAS on their app with the OneSignal Expo Plugin integrated?

**Comment by jparksecurity** [comment]
@rgomezp 

I have successfully set up EAS on my app with the OneSignal Expo Plugin integrated.

FYI, I use [local credential ](https://docs.expo.dev/app-signing/local-credentials/), and I have no idea if it would make any difference on this particular issue.

However, I can not use this plugin on production now because of a few problems:
1. Onesignal extension version/build number match (iOS only) #53
2. Deeplink opens in-app browser #47 
3. Push notification (iOS only) #56 
4. keychain (iOS only) #57

**Comment by javascripter** [comment]
So far I haven't been able to build successfully on EAS with EAS managed credentials and I still use 1.0.0-beta7 in my app which does not require ONSE.

In my observation running `eas prebuild` locally generates an iOS project with automatic signing on, but somehow still shows `Automatic signing is disabled` error on EAS. I'm not sure why.

**Comment by frossetto** [comment]
@rgomezp Sorry for the late reply, I followed the steps for all the links and I can relate to the same issue that @javascripter has;

**Comment by GautierT** [comment]
Hi
Same problem : 

```
❌  error: No profiles for 'io.PROJECT.OneSignalNotificationServiceExtension' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'io.PROJECT.OneSignalNotificationServiceExtension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'OneSignalNotificationServiceExtension' from project 'PROJECT')
```

**Comment by raunaqsingh2020** [comment]
> I'd like to gauge the level of success from everyone else while building with EAS. Has _anyone_ here been able to successfully set up EAS on their app with the OneSignal Expo Plugin integrated?

Sorry for the late reply. I was able to successfully set it up! Here's what my final setup process looked like:

I had to create and use local credentials (different ones for production and development). So, make sure to have  `"credentialsSource": "local"` in your eas.json file.

On the Apple developer console (developer.apple.com), I created two identifiers: `com.PROJECT.mobileapp` and `com.PROJECT.mobileapp.OneSignalNotificationServiceExtension`.

Next, create provisioning profiles on the Apple developer console as well. I created both Ad hoc and App Store provisioning profiles (for local development and production builds respectively) with both identifiers (4 provisioning profiles in total). Then, download the provisioning files (.mobileprovision) and place them somewhere in your directory.

My credentials.json file looked like this:

```
{
    "ios": {
        "<PROJECT>": {
            "distributionCertificate": {
                "path": "ios/certs/ios_distribution_certificate.p12",
                "password": "***"
            },
            "provisioningProfilePath": "ios/certs/prod/***mobileappprofile.mobileprovision"
        },
        "OneSignalNotificationServiceExtension": {
            "distributionCertificate": {
                "path": "ios/certs/ios_distribution_certificate.p12",
                "password": "***"
            },
            "provisioningProfilePath": "ios/certs/prod/***onesignalprofile.mobileprovision"
        }
    }
}
```

Hopefully that helps!

**Comment by lisaah** [comment]
I haven't revisited this for iOS yet; we went with using expo-notifications with native tokens for now.

**Comment by russriser** [comment]
I was able to successfully build with EAS managed workflow by using local credentials as @r1cs1 and @raunaqsingh2020 described.

I have a couple notes for creating a new identifier and provisioning profiles in the apple dev portal....

- when creating a new identifier for the OneSignalNotificationServiceExtension
     - select AppId from the list of identifier types
     - select App when choosing between App and App Clip
     - add the App Groups capability with the group.BUNDLEID.xxx.onesignal
     - do NOT add push notifications capability to the new identifier
- when modifying your existing com.BUNDLEID.xxx identifier (your app)
     - add the App Groups capability with the group.BUNDLEID.xxx.onesignal
     - keep/add the push notifications capability
- when creating new provisioning profiles
     - a new provisioning profile is needed for each of the two identifiers
     - both provisioning profiles should use the same distribution certificate that is used by your app
- when declaring your credentials in credentials.json
     - use the same distribution certificate for the OneSignalNotificationServiceExtension as is used for your app (no need to  create a new cert)
     
one last note: make sure to build with BOTH identifiers containing the AppGroup simultaneously. I tried to build with just the OneSignalNotificationServiceExtension having the AppGroup, then added the capability to the main app identifier when it didn't work.....but doing them one by one screwed something up. I then had to remove both, rebuild to get the original error, then build it again with both identifiers enabling the AppGroup capability.

**Comment by rgomezp** [comment]
Thank you everyone for helping out. I will put together a guide to make this process easier!

**Comment by rgomezp** [comment]
Update: I went ahead and put together a guide that can be found in [the discussion forums](https://github.com/OneSignal/onesignal-expo-plugin/discussions/63).

If you would like to make suggestions on the doc before it is finalized, please leave a comment in the above-linked discussion thread.

Thanks for everyone who helped.

Also included below.

---
# Provisioning Setup for iOS
## 1. Credentials Setup
To build successfully, you will need to create and use local credentials (one for production and development). Add `"credentialsSource": "local"` to your `eas.json` file.

## 2. Identifiers
In your [Apple developer console](developer.apple.com) create two identifiers with the following format:
   - `com.PROJECT.mobileapp`
   - `com.PROJECT.mobileapp.OneSignalNotificationServiceExtension`

### When modifying your existing main app identifier:
   - add the App Groups capability like so: `group.<identifier>.onesignal`
   - keep / add the "Push Notifications" capability

### When creating a new identifier for `OneSignalNotificationServiceExtension`:
   - select AppId from the list of identifier types
   - select App when choosing between App and App Clip
   - add the App Groups capability like so: `group.<identifier>.onesignal`
   - do not add the "Push Notifications" capability

### Note on App Groups:
Make sure to build with both identifiers containing the AppGroup simultaneously. To troubleshoot, remove them both and then rebuild with both identifiers' AppGroup capabilities enabled.

## 3. Provisioning
Create Ad hoc (local development) and App Store (production) provisioning profiles with both identifiers (4 provisioning profiles total). Both provisioning profiles should use the same distribution certificate that is used by your app. Download the profiles.

## 4. Add the profiles to your `credentials.json` file:
Use the same distribution certificate for the OneSignalNotificationServiceExtension as is used for your app (no need to create a new cert).

```
{
    "ios": {
        "<PROJECT>": {
            "distributionCertificate": {
                "path": "ios/certs/ios_distribution_certificate.p12",
                "password": "***"
            },
            "provisioningProfilePath": "ios/certs/prod/***mobileappprofile.mobileprovision"
        },
        "OneSignalNotificationServiceExtension": {
            "distributionCertificate": {
                "path": "ios/certs/ios_distribution_certificate.p12",
                "password": "***"
            },
            "provisioningProfilePath": "ios/certs/prod/***onesignalprofile.mobileprovision"
        }
    }
}
```

**Comment by tsheaff** [comment]
So if I'm hearing this right, the "solution" here is that if we want to use OneSignal with Expo, we lose the (huge) benefit of having Expo manage our provisioning credentials for us? That's quite frustrating, and it seems like something that really shouldn't be necessary here. Why is the separate `OneSignalNotificationServiceExtension` even necessary in the first place?

**Comment by tsheaff** [comment]
Also @rgomezp the link to that discussion forum is giving me a 404: https://github.com/OneSignal/onesignal-expo-plugin/discussions/63

**Comment by russriser** [comment]
@tsheaff at the time this PR was closed Expo had no way of managing credentials for projects with multiple targets (your app and the OS service extension are each a target). This capability might exist now, but I'm not sure. At the time, Expo had JUST made an update to their EAS build process which enabled multi-taget builds under the managed workflow...prior to that you would have had to eject from Expo completely.

The NotificationServiceExtension is a fairly recent requirement by Apple. One cannot utilize push notifications without an extension. And this extension becomes a new "target" in XCode builds. Since Expo runs the XCode builds for you, any XCode settings you want to use need to be implemented in EAS. Implementing every XCode setting is impractical, so they prioritize the most used settings. 

So again, they might have implemented multi-target credentials management by now (I don't know), but we should be glad they've implemented multi-target builds at all

**Comment by tsheaff** [comment]
Thanks @russriser great answer!

As for the `credentials.json` itself, it requires a password and a `.p12` rather than just the `.cer`. When I download the cert from the [Apple Developer Center](https://developer.apple.com/account/resources/certificates/list), I'm only getting the .cer. Does this mean I need to first create a new certificate for App Store? And if so, do I need two, once for the `OneSignalNotificationServiceExtension` and one for the non-`OneSignalNotificationServiceExtension` App Id? Specifically referring to these screens:

![Screenshot 2023-08-07 at 17 28 47](https://github.com/OneSignal/onesignal-expo-plugin/assets/1238684/eabc92b5-abde-41da-927b-b2b8cf1db03c)

![Screenshot 2023-08-07 at 17 29 34](https://github.com/OneSignal/onesignal-expo-plugin/assets/1238684/2a218a09-3ad4-49a8-b7e0-82f66697923a)


Thanks for the help! This has been managed by EAS previously, and the guide here is a bit incomplete w/r/t certificates (it's very thorough regarding the App IDs / App Groups piece)

**Comment by tsheaff** [comment]
Oh I think I misread that UI. I thought I was adding APNS to the cert, but it's an either/or, I think "iOS Distrbution" is the one I want. Trying that now.

**Comment by russriser** [comment]
@tsheaff You should be able to use a single distribution certificate for everything. But things may have changed a bit in the year+ since I set this up. I don't remember creating an Apple Push Notification Service SSL. That might be new, or you might not need to do that.

**Comment by rignaneseleo** [comment]
I had this error during my build with Codemagic.io 

I created a ipa file from xcode (flutter build ipa) and pushed that to testflight: that created a provisioning profile for me and now it compiles fine.

**Comment by chiragsahu** [comment]
I was facing an error related to provisioning profiles while working on my project. Here’s what worked for me:

I realized that I was selecting the provisioning profile linked to my Apple ID Team instead of using the one associated with my project's team. Switching to the correct provisioning profile resolved the issue.

Solution
Make sure to select the appropriate provisioning profile from your project's team rather than the one tied to your Apple ID.

**Comment by rgomezp** [comment]
> @rgomezp We have custom targets in our app that automatically get credentials generated for them in EAS builds, using the Expo Apple Targets plugin: https://github.com/EvanBacon/expo-apple-targets/tree/main/apps
> 
> Could that be a good way to do credential handling?

I'm not familiar with that plugin unfortunately. It looks like it's still experimental. However, the intended purpose appears to be target management rather than credential handling.

Expo should automatically create credentials based on the targets you have. I suppose it's possible that plugin is removing the OneSignal extension target.

I would suggest putting this plugin first in your plugin config and seeing if that helps. If that doesn't work, remove EvanBacon's plugin, make sure you can get this plugin working without it, and then try re-adding it.

**Comment by nixolas1** [comment]
You were completely right. It did a overwrite of the extension target array.
Thank you so much!

**Comment by appfr3d** [comment]
I had the exact same error and experience as you [nixolas1](https://github.com/nixolas1). Once I placed the `onesignal-expo-plugin` plugin **after** the `expo-apple-targets` plugin in the plugin array, everything worked as expected!

From:
```js
plugins: [
   ...,
    [
      'onesignal-expo-plugin',
      {
        mode: 'development',
        devTeam: 'XXX',
      },
    ],
    [
      '@bacons/apple-targets',
      {
        appleTeamId: 'XXX',
      },
    ],
  ...,
  ],
``` 

to: 
```js
plugins: [
   ...,
    [
      '@bacons/apple-targets',
      {
        appleTeamId: 'XXX',
      },
    ],
    [
      'onesignal-expo-plugin',
      {
        mode: 'development',
        devTeam: 'XXX',
      },
    ],
  ...,
  ],
```

**Comment by jqn** [comment]
In my case this resolved the issue npx expo prebuild --platform ios --clean
