### ISSUE TITLE
[Bug]: Several Android users added, none correct

### ISSUE THREAD

**Issue by humbertocruz** [OneSignal/onesignal-expo-plugin#86]
### What happened?

After build the Expo App, upload it to google play and install on my google device, the onesignal sdk starts up and registered about 6 new users. After that, another 4... I tried to send a push notifications, but 9 is not subcribed and one is Google Play Services Library error.
I follow the ExpoSDK and build the app using Expo EAS
I did not make the ExpoSDK step 2.5 because I don't want to eject from expo.
Any help ?

### Steps to reproduce?

```Markdown
1. Follow Expo SDK Setup
2. Configure app.json
3. Add google-service.json into app.json
3.1 - Add OneSignal.setAppId('appid') to App.tsx
4. Connect my firebase to the app com.humbertocruz.brasalapp
5. Build App with eas build - p android
6. Transfer to Google Play on a new app
7. Add a Internal Test version
8. Donload the App on GooglePlay
9. Run the app
```

### What did you expect to happen?

One user from my phone (Sansung A71) created and receive a notification push

### OneSignal Expo SDK version

"onesignal-expo-plugin": "^1.0.1"
"react-native-onesignal": "^4.3.7",

### Platform

Android

### Relevant log output

```Shell
nothing from my app side
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@humbertocruz Thanks for reporting, I'll reply to each part of your question inline.

> ### What happened?

> After build the Expo App, upload it to google play and install on my google device, the onesignal sdk starts up and registered about 6 new users. After that, another 4...

There will be a OneSignal Users / Players for each device you install your app on. If you uninstall then reinstall your app (or clear all app data from the device settings) then open the app again OneSignal will see this as a new Users. Since nothing carries over through this.

> but 9 is not subcribed and one is Google Play Services Library error.

This could happen due to a number of reasons, to find the root of the cause you will need to pull the logcat from the device with ADB or Android Studio.

> ### Steps to reproduce?
> 6. Transfer to Google Play on a new app
> 7. Add a Internal Test version
> 8. Donload the App on GooglePlay

Could you share the APK or link for this? Someone can verify if the issue is with the app or device.
Also if possible could you share the project?
I recommend trying to create a new expo project to see if you have the same issue, this can help rule out if the issue is with your specific project or not.

> ### What did you expect to happen?
One user from my phone (Sansung A71) created and receive a notification push

Do you get the same problem on other Android devices or Android Emulators?

**Comment by rgomezp** [comment]
Closing due to no response
