### ISSUE TITLE
[Bug]: Intermittent "ITMS-90078: Missing Push Notification Entitlement" on Testflight

### ISSUE THREAD

**Issue by Amrit0991** [OneSignal/onesignal-expo-plugin#98]
### What happened?

Hi,

The majority of my builds receive the "ITMS-90078: Missing Push Notification Entitlement" error when I submit them to Testflight. Occasionally, I can get a successful build, but I can't isolate exactly what causes that to happen.

Happy to provide logs and help debug, as this has significantly slowed down our deploy process. 

Thanks in advance for your help everyone!

### Steps to reproduce?

```Markdown
1. Install expo 45.0.0
2. Run eas build
3. Run eas submit -p ios once done building
```

### What did you expect to happen?

Expected to have a working build with all capabilities enabled, but both Apple Sign In and Push Notifications don't work. I get the "Missing Push Capability" error when sending user data to OneSignal.

### OneSignal Expo SDK version

1.0.2

### Platform

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rgomezp** [comment]
Howdy Amrit,
Thanks for opening an issue.

Are you using local credentials or managed?

If you could please provide your redacted EAS/expo config files, credentials, or other relevant files that would be useful.

This issue was resolved in the latest release after the Expo made some changes to treat multiple iOS targets separately when bundling entitlements. You can read more about that [issue here](https://github.com/OneSignal/onesignal-expo-plugin/blob/main/IOS_CREDENTIALS_EAS.md) (collapsed section).

Cheers

**Comment by Amrit0991** [comment]
Hi @rgomezp - closing this issue for now as I was able to get a working build after restarting my Mac and getting the newest OSX and presumably the newest XCode. Then I ran `eas credentials` again.
